### ISSUE TITLE
no return value for adding new edge using adjaceny

### ISSUE THREAD

**Issue by mohataher** [tinkerpop/frames#111]
Shouldn't we return this value instead of not handling it?
https://github.com/tinkerpop/frames/blob/master/src/main/java/com/tinkerpop/frames/annotations/AdjacencyAnnotationHandler.java#L53

**Comment by spmallette** [comment]
I don't have an answer for you, but I think you should take a look at:

https://github.com/BrynCooke/totorom

or 

https://github.com/Syncleus/Ferma

Given the development of TinkerPop3 ( http://tinkerpop.incubator.apache.org/ ) it's unlikely that we will make additional changes to frames at this time.

**Comment by mohataher** [comment]
Well, thanks for your answer.
